config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
   validates :title, presence: true, length: { minimum: 2 }
   validates :description, presence: true, length: { maximum: 500 }
   belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { minimum: 2 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true , format:{with:VALID_EMAIL_REGEX}
  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  @posts = Post.all
end

def new
  @post = Post.new
end

def create
  @user = User.find_by(name:"cristin")
  @post = @user.posts.create(post_params)
   redirect_to posts_path
end

def show
  @post = Post.find(params[:id])
end

def edit
  @post = Post.find(params[:id])
end

def update
  @post = Post.find(params[:id])
  if @post.update(post_params)
    redirect_to posts_path, notice: "Post editado"
  else
    render :edit
  end
end

def destroy
  post = post.find(params[:id])
  post.destroy
  redirect_to posts_path, notice: "post eliminado"
end
private
  def post_params
    params.require(:post).permit(:title,:description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  @users = User.all
end

def new
  @user = User.new
end

def create
  @user = User.new(user_params)
  if @User.save
    redirect_to users_path, notice: "El usuario fue creado con éxito"
  else
    render :new
  end
end

def show
  @user = User.find(params[:id])
end

def edit
  @user = User.find(params[:id])
end

def update
  @user = Product.find(params[:id])
  if @user.update(product_params)
    redirect_to users_path, notice: "El usuario ha sido editadocon éxito"
  else
    render :edit
  end
end

def destroy
  user = user.find(params[:id])
  user.destroy
  redirect_to users_path, notice: "El usuario fue eliminado con éxito"
end

private
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def form_title
    @post.new_record? ? "New post" : "Edit Post"
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def form_title
    @user.new_record? ? "Create User" : "Edit User"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hakaton</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= render partial: "partials/navbar", locals: {zone: "Canario"} %>
      <% if flash[:notice] %>
      <div class="alert alert-info"><%= flash[:notice] %></div>
      <% end %>
    <%= yield %>



    <footer>
     <%= render partial: "partials/footer" %>
    </footer>

  </body>
</html>

app/views/partials/_footer.html.erb
<div class="container">
  <div class="row justify-content-md-center">
  <p>2018 all rights reserved</p>
</div>
</div>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-dark bg-dark navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#"><%= zone %>
    <img src="/app/assets/images/bird.png" width="30" height="30" class="d-inline-block align-top" alt="">

  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/posts/edit.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-sm-6">

<h1>Edit post!</h1>
<%= form_for @post do |f| %>
<div class="form-group">
  <%= f.text_field :title, placeholder: "Titulo!" %>
 </div>
 <div class="form-group">
  <%= f.text_area :description, placeholder: "Escribe el post!" %>
 </div>
  <div>
  <%= f.submit " Edit Post", class: "btn btn-dark btn-lg btn-block"%>
  </div>
<% end %>
</div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="row justify-content-md-center">
      <div class="col-sm-6">

          <h1>posts!</h1>
          <table class="table table-bordered">
            <thead class="thead-dark">
              <tr>
                <th scope="col">user</th>
                <th scope="col">Titulo</th>
                <th scope="col">Descripcion</th>
                <th scope="col">Editar Post</th>
                <th scope="col">Eliminar Post</th>
              </tr>
              </thead>
              <tbody>
            <% @posts.each do |post| %>
              <tr>
                <td><%= post.user.name%></td>
                <td><%= link_to post.title,post%></td>
                <td><%= post.description %></td>
                <td><%= link_to "Edit", edit_post_path(post) %></td>
                <td><%= link_to "Delete", post, method: :delete, data: { confirm: "¿Estás seguro de eliminar este post?" } %></td>
              </tr>
            <% end %>
            </tbody>
          </table>

          <div class="">
          <%= link_to "New Post", new_post_path, class: "btn btn-dark" %>
          </div>

</div>
</div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-sm-6">

<h1>Create New post!</h1>
<%= form_for @post do |f| %>
<div class="form-group">
  <%= f.text_field :title, placeholder: "Titulo!" %>
 </div>
 <div class="form-group">
  <%= f.text_area :description, placeholder: "Escribe el post!" %>
 </div>
  <div>
  <%= f.submit "Post", class: "btn btn-dark btn-lg btn-block"%>
  </div>
<% end %>
</div>
  </div>
</div>

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-sm-6">
      <h1><%= form_title %></h1>
      <%= form_for @user do |f| %>
        <div class="form-group">
          <%= f.text_field :name, class: "form-control input-lg", placeholder: "Ingresa el nombre de usuario" %>
        </div>
        <div class="form-group">
          <%= f.url_field :email, class: "form-control input-lg", placeholder: "Ingresa el email del usuario" %>
        </div>
        <div>
          <%= f.submit form_title, class: "btn btn-dark btn-lg btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<div class="container">
  <div class="row justify-content-md-center">
      <div class="col-sm-6">


<h1>Todos los usuarios</h1>

<table class="table table-bordered">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Nombre</th>
      <th scope="col">Email</th>
      <th scope="col">Editar Usuario</th>
      <th scope="col">Eliminar Usuario</th>
    </tr>
    </thead>
    <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= link_to user.name, user %></td>
      <td><%= user.email %></td>
      <td><%= link_to "Edit", edit_user_path(user) %></td>
      <td><%= link_to "Delete", user, method: :delete, data: { confirm: "¿Estás seguro de eliminar este usuario?" } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<div class="">
<%= link_to "Create New User", new_user_path, class: "btn btn-dark" %>
</div>

  </div>
 </div>
</div>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<div class="container">
<div class="row justify-content-md-center">
    <div class="col-sm-4">
      <h1>Usuario</h1>
      <ul class="list-group">
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <%= @user.name %>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
        <%= @user.email %>
        </li>
      </ul>



    </div>
  </div>
  </div>